import {
  IconAlertHexagon,
  IconArrowLeft,
  IconAt,
  IconBrandDiscordFilled,
  IconBrandGoogleFilled,
  IconChevronCompactDown,
  IconChevronLeft,
  IconDiscountCheck,
  IconDiscountCheckFilled,
  IconDownload,
  IconLoader,
  IconLock,
  IconQrcode,
  IconQuestionMark,
  IconSend,
  IconUserCircle,
  IconWritingSign,
  IconWritingSignOff,
  IconCheck,
  IconChevronDown,
  IconChevronUp,
} from '@tabler/icons-react';

const ICONS = {
  'arrow-left': IconArrowLeft,
  loader: IconLoader,
  discord: IconBrandDiscordFilled,
  google: IconBrandGoogleFilled,
  'discount-check': IconDiscountCheckFilled,
  'discount-check-outline': IconDiscountCheck,
  alert: IconAlertHexagon,
  'chevron-compact-down': IconChevronCompactDown,
  'chevron-left': IconChevronLeft,
  lock: IconLock,
  at: IconAt,
  qrcode: IconQrcode,
  'question-mark': IconQuestionMark,
  send: IconSend,
  'user-circle': IconUserCircle,
  download: IconDownload,
  pencil: IconWritingSign,
  'pencil-off': IconWritingSignOff,
  check: IconCheck,
  'chevron-down': IconChevronDown,
  'chevron-up': IconChevronUp,
};

export default ICONS;
