import {
  IconAlertHexagon,
  IconAlertTriangle,
  IconArrowLeft,
  IconAt,
  IconBellFilled,
  IconBrandDiscordFilled,
  IconBrandGoogleFilled,
  IconCheck,
  IconChecks,
  IconChevronCompactDown,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircleCheck,
  IconCircleCheckFilled,
  IconCirclePlus,
  IconCurrentLocation,
  IconDevices,
  IconDiscountCheck,
  IconDiscountCheckFilled,
  IconDownload,
  IconExclamationCircle,
  IconExternalLink,
  IconEye,
  IconEyeSearch,
  IconLayout,
  IconLoader,
  IconLock,
  IconLogout,
  IconMapPin,
  IconMapPinExclamation,
  IconMessage2,
  IconMessageCircle,
  IconMotorbike,
  IconPhone,
  IconPhotoEdit,
  IconQrcode,
  IconQuestionMark,
  IconScan,
  IconSend,
  IconShoppingBag,
  IconStar,
  IconStarFilled,
  IconStarHalfFilled,
  IconTrash,
  IconUser,
  IconUserCircle,
  IconUserQuestion,
  IconWritingSign,
  IconWritingSignOff,
  IconX,
  IconCalendarMonth,
  IconBrandGithub,
  IconHeart,
} from '@tabler/icons-react';

const ICONS = {
  'arrow-left': IconArrowLeft,
  loader: IconLoader,
  discord: IconBrandDiscordFilled,
  google: IconBrandGoogleFilled,
  'discount-check': IconDiscountCheckFilled,
  'discount-check-outline': IconDiscountCheck,
  alert: IconAlertHexagon,
  'chevron-compact-down': IconChevronCompactDown,
  'chevron-left': IconChevronLeft,
  lock: IconLock,
  at: IconAt,
  qrcode: IconQrcode,
  'question-mark': IconQuestionMark,
  send: IconSend,
  'user-circle': IconUserCircle,
  download: IconDownload,
  pencil: IconWritingSign,
  'pencil-off': IconWritingSignOff,
  check: IconCheck,
  'chevron-down': IconChevronDown,
  'chevron-up': IconChevronUp,
  bell: IconBellFilled,
  checks: IconChecks,
  'photo-edit': IconPhotoEdit,
  'external-link': IconExternalLink,
  'exclamation-circle': IconExclamationCircle,
  'alert-triangle': IconAlertTriangle,
  user: IconUser,
  message: IconMessage2,
  devices: IconDevices,
  layout: IconLayout,
  logout: IconLogout,
  motorbike: IconMotorbike,
  'chevron-right': IconChevronRight,
  x: IconX,
  phone: IconPhone,
  trash: IconTrash,
  'shopping-bag': IconShoppingBag,
  'circle-check': IconCircleCheck,
  eye: IconEye,
  'message-circle': IconMessageCircle,
  'circle-check-filled': IconCircleCheckFilled,
  scan: IconScan,
  'eye-search': IconEyeSearch,
  'user-question': IconUserQuestion,
  star: IconStar,
  'star-filled': IconStarFilled,
  'star-half-filled': IconStarHalfFilled,
  'current-location': IconCurrentLocation,
  'map-pin': IconMapPin,
  'map-pin-exclamation': IconMapPinExclamation,
  'circle-plus': IconCirclePlus,
  github: IconBrandGithub,
  heart: IconHeart,
};

export default ICONS;
