name: Unit Tests

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches: [dev, main]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # This step checks out your code repository.
      - name: Run Tests
        working-directory: ./utils
        run: |
          cd ./utils  # Change to the 'utils' directory
          pnpm install
          pnpm test
