name: Unit Tests

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches: [dev, main]

jobs:
  Jest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./utils
    steps:
      - uses: actions/checkout@v2  # This step checks out your code repository.
      - name: Run Tests
        run: |
          pnpm install
          pnpm test
