name: Unit Tests

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches: [dev, main]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
      - name: Run Tests
        working-directory: ./utils
        run: |
          pnpm install
          pnpm test