name: Unit Tests

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches: [dev, main]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          pnpm install
          pnpm test